// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserModel = "user_model"

// UserModel mapped from table <user_model>
type UserModel struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                              // 主键ID
	UserID          int64          `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                                         // 用户ID
	Name            string         `gorm:"column:name;not null;comment:模型显示名称（用户维度唯一）" json:"name"`                                                     // 模型显示名称（用户维度唯一）
	ModelKey        string         `gorm:"column:model_key;not null;comment:模型标识（doubao-1.5-vision-lite-250315）" json:"model_key"`                      // 模型标识（doubao-1.5-vision-lite-250315）
	Protocol        string         `gorm:"column:protocol;not null;comment:协议类型（openai/ark/claude/gemini/deepseek/ollama/qwen/ernie）" json:"protocol"`  // 协议类型（openai/ark/claude/gemini/deepseek/ollama/qwen/ernie）
	BaseURL         string         `gorm:"column:base_url;not null;comment:API 基础地址" json:"base_url"`                                                   // API 基础地址
	APIKeyEncrypted string         `gorm:"column:api_key_encrypted;not null;comment:加密后的 API 密钥" json:"api_key_encrypted"`                              // 加密后的 API 密钥
	ConfigJSON      string         `gorm:"column:config_json;comment:额外配置（如区域、访问密钥等）" json:"config_json"`                                               // 额外配置（如区域、访问密钥等）
	SecretHint      string         `gorm:"column:secret_hint;not null;comment:密钥脱敏提示（如显示末尾4位）" json:"secret_hint"`                                      // 密钥脱敏提示（如显示末尾4位）
	ProviderName    string         `gorm:"column:provider_name;not null;comment:提供商名称（如 OpenAI、Ark、DeepSeek）" json:"provider_name"`                     // 提供商名称（如 OpenAI、Ark、DeepSeek）
	MetaID          int64          `gorm:"column:meta_id;comment:关联全局 model_meta.id（继承能力/图标）" json:"meta_id"`                                           // 关联全局 model_meta.id（继承能力/图标）
	DefaultParams   string         `gorm:"column:default_params;comment:默认参数（如 temperature、max_tokens）" json:"default_params"`                          // 默认参数（如 temperature、max_tokens）
	Scope           int32          `gorm:"column:scope;not null;default:7;comment:使用范围（位掩码：1=智能体, 2=应用, 4=工作流）" json:"scope"`                           // 使用范围（位掩码：1=智能体, 2=应用, 4=工作流）
	Status          int32          `gorm:"column:status;not null;default:1;comment:状态（0=禁用, 1=启用）" json:"status"`                                       // 状态（0=禁用, 1=启用）
	IsDefault       int32          `gorm:"column:is_default;not null;comment:是否为默认（0=不是, 1=是）" json:"is_default"`                                       // 是否为默认（0=不是, 1=是）
	CreatedAt       time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);autoCreateTime:milli;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3);autoUpdateTime:milli;comment:更新时间" json:"updated_at"` // 更新时间
	Deleted         bool           `gorm:"column:deleted;not null;comment:删除状态（0=未删除, 1=已删除）" json:"deleted"`                                           // 删除状态（0=未删除, 1=已删除）
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间（逻辑删除）" json:"deleted_at"`                                                      // 删除时间（逻辑删除）
}

// TableName UserModel's table name
func (*UserModel) TableName() string {
	return TableNameUserModel
}
