// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username  string         `gorm:"column:username;not null" json:"username"`
	Email     string         `gorm:"column:email;not null" json:"email"`
	Password  string         `gorm:"column:password;not null" json:"password"`
	Role      string         `gorm:"column:role;not null;default:user" json:"role"`
	Avatar    string         `gorm:"column:avatar;comment:头像" json:"avatar"` // 头像
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);autoCreateTime:milli" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3);autoUpdateTime:milli" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Deleted   bool           `gorm:"column:deleted" json:"deleted"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
