// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package developer_api

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type ModelClass int64

const (
	ModelClass_GPT    ModelClass = 1
	ModelClass_SEED   ModelClass = 2
	ModelClass_Claude ModelClass = 3
	// name: MiniMax
	ModelClass_MiniMax         ModelClass = 4
	ModelClass_Plugin          ModelClass = 5
	ModelClass_StableDiffusion ModelClass = 6
	ModelClass_ByteArtist      ModelClass = 7
	ModelClass_Maas            ModelClass = 9
	// Abandoned: Qianfan (Baidu Cloud)
	ModelClass_QianFan ModelClass = 10
	// name：Google Gemini
	ModelClass_Gemini ModelClass = 11
	// name: Moonshot
	ModelClass_Moonshot ModelClass = 12
	// Name: Zhipu
	ModelClass_GLM ModelClass = 13
	// Name: Volcano Ark
	ModelClass_MaaSAutoSync ModelClass = 14
	// Name: Tongyi Qianwen
	ModelClass_QWen ModelClass = 15
	// name: Cohere
	ModelClass_Cohere ModelClass = 16
	// Name: Baichuan Intelligent
	ModelClass_Baichuan ModelClass = 17
	// Name: ERNIE Bot
	ModelClass_Ernie ModelClass = 18
	// Name: Magic Square
	ModelClass_DeekSeek ModelClass = 19
	// name: Llama
	ModelClass_Llama   ModelClass = 20
	ModelClass_StepFun ModelClass = 23
	ModelClass_Other   ModelClass = 999
)

func (p ModelClass) String() string {
	switch p {
	case ModelClass_GPT:
		return "GPT"
	case ModelClass_SEED:
		return "SEED"
	case ModelClass_Claude:
		return "Claude"
	case ModelClass_MiniMax:
		return "MiniMax"
	case ModelClass_Plugin:
		return "Plugin"
	case ModelClass_StableDiffusion:
		return "StableDiffusion"
	case ModelClass_ByteArtist:
		return "ByteArtist"
	case ModelClass_Maas:
		return "Maas"
	case ModelClass_QianFan:
		return "QianFan"
	case ModelClass_Gemini:
		return "Gemini"
	case ModelClass_Moonshot:
		return "Moonshot"
	case ModelClass_GLM:
		return "GLM"
	case ModelClass_MaaSAutoSync:
		return "MaaSAutoSync"
	case ModelClass_QWen:
		return "QWen"
	case ModelClass_Cohere:
		return "Cohere"
	case ModelClass_Baichuan:
		return "Baichuan"
	case ModelClass_Ernie:
		return "Ernie"
	case ModelClass_DeekSeek:
		return "DeekSeek"
	case ModelClass_Llama:
		return "Llama"
	case ModelClass_StepFun:
		return "StepFun"
	case ModelClass_Other:
		return "Other"
	}
	return "<UNSET>"
}

func ModelClassFromString(s string) (ModelClass, error) {
	switch s {
	case "GPT":
		return ModelClass_GPT, nil
	case "SEED":
		return ModelClass_SEED, nil
	case "Claude":
		return ModelClass_Claude, nil
	case "MiniMax":
		return ModelClass_MiniMax, nil
	case "Plugin":
		return ModelClass_Plugin, nil
	case "StableDiffusion":
		return ModelClass_StableDiffusion, nil
	case "ByteArtist":
		return ModelClass_ByteArtist, nil
	case "Maas":
		return ModelClass_Maas, nil
	case "QianFan":
		return ModelClass_QianFan, nil
	case "Gemini":
		return ModelClass_Gemini, nil
	case "Moonshot":
		return ModelClass_Moonshot, nil
	case "GLM":
		return ModelClass_GLM, nil
	case "MaaSAutoSync":
		return ModelClass_MaaSAutoSync, nil
	case "QWen":
		return ModelClass_QWen, nil
	case "Cohere":
		return ModelClass_Cohere, nil
	case "Baichuan":
		return ModelClass_Baichuan, nil
	case "Ernie":
		return ModelClass_Ernie, nil
	case "DeekSeek":
		return ModelClass_DeekSeek, nil
	case "Llama":
		return ModelClass_Llama, nil
	case "StepFun":
		return ModelClass_StepFun, nil
	case "Other":
		return ModelClass_Other, nil
	}
	return ModelClass(0), fmt.Errorf("not a valid ModelClass string")
}

func ModelClassPtr(v ModelClass) *ModelClass { return &v }
func (p *ModelClass) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ModelClass(result.Int64)
	return
}

func (p *ModelClass) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}
