// Code generated by hertz generator.

package mianshiba

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createusermodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _modelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkusermodelconfiguredMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listusermodelsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteusermodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detailsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getusermodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateusermodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passwordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _forgotpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wechatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wechatcallbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wechatloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresumelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recordresumedeleteinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresumedeleteurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresumedetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresumedownloadurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _metaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _saveresumemetainfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresumeuploadurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delete0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
