// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameResume = "resume"

// Resume 用户简历元信息表
type Resume struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	UserID          int64          `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                 // 用户ID
	FileKey         string         `gorm:"column:file_key;not null;comment:对象存储中的文件唯一标识" json:"file_key"`                       // 对象存储中的文件唯一标识
	Filename        string         `gorm:"column:filename;not null;comment:原始文件名" json:"filename"`                              // 原始文件名
	Filetype        string         `gorm:"column:filetype;comment:文件类型，如 pdf/docx" json:"filetype"`                             // 文件类型，如 pdf/docx
	Filesize        int64          `gorm:"column:filesize;comment:文件大小（字节）" json:"filesize"`                                    // 文件大小（字节）
	Status          int32          `gorm:"column:status;not null;default:1;comment:简历状态：1已上传 2解析中 3已解析 4已删除 5失败" json:"status"` // 简历状态：1已上传 2解析中 3已解析 4已删除 5失败
	ParseStatus     int32          `gorm:"column:parse_status;not null;comment:解析状态：0未开始 1解析中 2成功 3失败" json:"parse_status"`     // 解析状态：0未开始 1解析中 2成功 3失败
	ParseError      string         `gorm:"column:parse_error;comment:解析失败原因摘要" json:"parse_error"`                              // 解析失败原因摘要
	UploadAt        time.Time      `gorm:"column:upload_at;not null;default:CURRENT_TIMESTAMP;comment:上传时间" json:"upload_at"`   // 上传时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;comment:软删除时间" json:"deleted_at"`                                   // 软删除时间
	Deleted         bool           `gorm:"column:deleted;not null;comment:删除状态（0=未删除, 1=已删除）" json:"deleted"`                   // 删除状态（0=未删除, 1=已删除）
	LlmParseContent string         `gorm:"column:llm_parse_content" json:"llm_parse_content"`
}

// TableName Resume's table name
func (*Resume) TableName() string {
	return TableNameResume
}
