// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package mianshiba

import (
	"github.com/apache/thrift/lib/go/thrift"
	"mianshiba/api/model/interview"
	"mianshiba/api/model/user"
)

type UserService interface {
	user.UserService
}

type UserServiceClient struct {
	*user.UserServiceClient
}

func NewUserServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: user.NewUserServiceClientFactory(t, f),
	}
}

func NewUserServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: user.NewUserServiceClientProtocol(t, iprot, oprot),
	}
}

func NewUserServiceClient(c thrift.TClient) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: user.NewUserServiceClient(c),
	}
}

type InterviewService interface {
	interview.InterviewService
}

type InterviewServiceClient struct {
	*interview.InterviewServiceClient
}

func NewInterviewServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *InterviewServiceClient {
	return &InterviewServiceClient{
		InterviewServiceClient: interview.NewInterviewServiceClientFactory(t, f),
	}
}

func NewInterviewServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *InterviewServiceClient {
	return &InterviewServiceClient{
		InterviewServiceClient: interview.NewInterviewServiceClientProtocol(t, iprot, oprot),
	}
}

func NewInterviewServiceClient(c thrift.TClient) *InterviewServiceClient {
	return &InterviewServiceClient{
		InterviewServiceClient: interview.NewInterviewServiceClient(c),
	}
}

type UserServiceProcessor struct {
	*user.UserServiceProcessor
}

func NewUserServiceProcessor(handler UserService) *UserServiceProcessor {
	self := &UserServiceProcessor{user.NewUserServiceProcessor(handler)}
	return self
}

type InterviewServiceProcessor struct {
	*interview.InterviewServiceProcessor
}

func NewInterviewServiceProcessor(handler InterviewService) *InterviewServiceProcessor {
	self := &InterviewServiceProcessor{interview.NewInterviewServiceProcessor(handler)}
	return self
}
