// Code generated by hertz generator.

package mianshiba

import (
	"context"
	interviewAPI "mianshiba/api/model/interview"
	"mianshiba/application/interview"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetResumeUploadUrl .
// @router /api/interview/resume/upload/url [GET]
func GetResumeUploadUrl(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviewAPI.ResumeUploadUrlRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := interview.InterviewApplicationSVC.GetResumeUploadUrl(ctx, req.GetFilename(), req.GetFiletype())
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// SaveResumeMetaInfo .
// @router /api/interview/resume/meta/save [POST]
func SaveResumeMetaInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviewAPI.ResumeMetaInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := interview.InterviewApplicationSVC.CreateResume(ctx, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetResumeDownloadUrl .
// @router /api/interview/resume/download/url [GET]
func GetResumeDownloadUrl(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviewAPI.ResumeDownloadUrlRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interviewAPI.ResumeDownloadUrlResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetResumeDeleteUrl .
// @router /api/interview/resume/delete/url [GET]
func GetResumeDeleteUrl(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviewAPI.ResumeDeleteUrlRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interviewAPI.ResumeDeleteUrlResponse)

	c.JSON(consts.StatusOK, resp)
}

// RecordResumeDeleteInfo .
// @router /api/interview/resume/delete/record [POST]
func RecordResumeDeleteInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviewAPI.ResumeDeleteInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interviewAPI.ResumeDeleteInfoResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetResumeList .
// @router /api/interview/resume/list [GET]
func GetResumeList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviewAPI.ResumeListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interviewAPI.ResumeListResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetResumeDetail .
// @router /api/interview/resume/detail/:file_key [GET]
func GetResumeDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviewAPI.ResumeDetailRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interviewAPI.ResumeDetailResponse)

	c.JSON(consts.StatusOK, resp)
}
