// Code generated by hertz generator.

package mianshiba

import (
	"context"
	"net/http"

	userAPI "mianshiba/api/model/user"
	"mianshiba/application/user"
	"mianshiba/conf"
	"mianshiba/pkg/hertzutil/domain"
	"mianshiba/pkg/jwt"
	"mianshiba/pkg/logs"

	mconsts "mianshiba/types/consts"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol"
	consts "github.com/cloudwego/hertz/pkg/protocol/consts"
)

// @router /api/user/create/model [POST]
func CreateUserModel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.CreateUserModelRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp, err := user.UserApplicationSVC.CreateUserModel(ctx, &req)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// ListUserModels .
// @router /api/user/model/list [GET]
func ListUserModels(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.ListUserModelsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userAPI.ListUserModelsResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetUserModel .
// @router /api/user/model/details/:id [GET]
func GetUserModel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.IDRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userAPI.GetUserModelResponse)

	c.JSON(consts.StatusOK, resp)
}

// UpdateUserModel .
// @router /api/user/model/update/:id [PUT]
func UpdateUserModel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.UpdateUserModelRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userAPI.UpdateUserModelResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteUserModel .
// @router /api/user/model/delete/:id [DELETE]
func DeleteUserModel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.IDRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userAPI.DeleteUserModelResponse)

	c.JSON(consts.StatusOK, resp)
}

// Register .
// @router /api/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp, jwtToken, err := user.UserApplicationSVC.Register(ctx, &req)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}

	c.SetCookie(jwt.TokenKey,
		jwtToken,
		mconsts.SessionMaxAgeSecond,
		"/", domain.GetOriginHost(c),
		protocol.CookieSameSiteDefaultMode,
		false, true)

	c.JSON(http.StatusOK, resp)
}

// Login .
// @router /api/user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(http.StatusBadRequest, err.Error())
		return
	}

	resp, jwtToken, err := user.UserApplicationSVC.Login(ctx, &req)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}

	logs.Infof("[Login] jwt token: %s", jwtToken)

	c.SetCookie(jwt.TokenKey,
		jwtToken,
		int(conf.Global.Security.JWTExpirationInt),
		"/", domain.GetOriginHost(c),
		protocol.CookieSameSiteDefaultMode,
		false, true)
	c.JSON(http.StatusOK, resp)
}

// GetProfile .
// @router /api/user/profile [GET]
func GetProfile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.EmptyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userAPI.GetProfileResponse)

	c.JSON(consts.StatusOK, resp)
}

// UpdateProfile .
// @router /api/user/profile [PUT]
func UpdateProfile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.UpdateProfileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userAPI.UpdateProfileResponse)

	c.JSON(consts.StatusOK, resp)
}

// WechatLogin .
// @router /api/user/wechat/login [GET]
func WechatLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.EmptyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userAPI.WechatLoginQRResponse)

	c.JSON(consts.StatusOK, resp)
}

// WechatCallback .
// @router /api/user/wechat/callback [GET]
func WechatCallback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.WechatCallbackRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userAPI.LoginResponse)

	c.JSON(consts.StatusOK, resp)
}

// CheckUserModelConfigured .
// @router /api/user/model/check [GET]
func CheckUserModelConfigured(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.EmptyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userAPI.CheckUserModelConfiguredResponse)

	c.JSON(consts.StatusOK, resp)
}

// ForgotPassword . TODO: 实现发送重置密码邮件的逻辑
// @router /api/user/password/forgot [POST]
func ForgotPassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.ForgotPasswordRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp, err := user.UserApplicationSVC.ForgotPassword(ctx, &req)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}

	c.JSON(http.StatusOK, resp)
}

// ResetPassword .
// @router /api/user/password/reset [POST]
func ResetPassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.ResetPasswordRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp, err := user.UserApplicationSVC.ResetPassword(ctx, &req)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}

	c.JSON(http.StatusOK, resp)
}

// Logout .
// @router /api/user/logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userAPI.EmptyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := user.UserApplicationSVC.Logout(ctx, &req)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}

	c.JSON(consts.StatusOK, resp)
}
